apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kid-data
  namespace: kid
spec:
  #storageClassName: faster
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi
