apiVersion: v1
kind: ConfigMap
metadata:
  name: config-default
  namespace: kid
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        location / {
          proxy_pass http://wordpress-svc.kid:1314;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header X-Forwarded-Proto https;
        }
    }