apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: kid
  labels:
     service: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30087
  selector:
    service: nginx